### ISSUE TITLE
1.8.4 broken version 

### ISSUE THREAD

**Issue by brunowego** [inorganik/countUp.js#163]
After upgrade from 1.8.3 to 1.8.4, I get:

```
TypeError: self.options.formattingFn is not a function
```

**Comment by inorganik** [comment]
Need more info, please paste the options object you are passing to CountUp

**Comment by brunowego** [comment]
The output stack:

```
TypeError: self.options.formattingFn is not a function
    at CountUp.self.printValue (countUp.js:130)
    at new CountUp (countUp.js:232)
    at count-up.js:19
    at fn (ember.debug.js:915)
    at invokeWithOnError (ember.debug.js:346)
    at Queue.flush (ember.debug.js:405)
    at DeferredActionQueues.flush (ember.debug.js:529)
    at Backburner.end (ember.debug.js:599)
    at Backburner.run (ember.debug.js:713)
    at Backburner._runExpiredTimers (ember.debug.js:1107)
```

My ember implementation:

```js
import Component from 'ember-component';
import CountUp from 'countup.js';
import observer from 'ember-metal/observer';
import { next } from 'ember-runloop';

export default Component.extend({
  tagName: 'span',

  didInsertElement() {
    this._insertAndStartCountUp();
  },

  changed: observer(
    'startVal', 'endVal', 'decimals', 'duration', 'useEasing', 'easingFn',
    'useGrouping', 'separator', 'decimal', 'prefix', 'suffix', 'formattingFn',
    'onComplete', function() {
      this._insertAndStartCountUp();
    }),

  // private

  _insertAndStartCountUp() {
    next(() => {
      let countup = new CountUp(
        this.get('elementId'),
        this.get('startVal') || 0,
        this.get('endVal') || 0,
        this.get('decimals') || 0,
        this.get('duration') || 2,
        {
          useEasing: this.get('useEasing'),
          easingFn: this.get('easingFn'),
          useGrouping: this.get('useGrouping'),
          separator: this.get('separator') || '.',
          decimal: this.get('decimal') || ',',
          prefix: this.get('prefix') || '',
          suffix: this.get('suffix') || '',
          formattingFn: this.get('formattingFn')
        }
      );

      if (this.attrs.onComplete) {
        countup.start(this.attrs.onComplete);
      } else {
        countup.start();
      }
    });
  }
});
```

Thanks, sorry for the delay.

**Comment by inorganik** [comment]
This line: `this.get('formattingFn')` is not returning a function. Did you test it? Put this in your code:

`console.log('formattingFn', this.get('formattingFn'))`.

I tested passing a custom formatting function to the current version of CountUp and it worked fine. Let me know what you find.
